#!/bin/bash
#This script is generated by teh Java code and serves the purpose of regenerating the network
#Creator: 1765180

#Creating a directory for the netkit lab
mkdir regenNetwork
cd regenNetwork
echo "Name of the directory that is created: regenNetwork"
echo "Path of the directory created:"
pwd

#The following two commands will create the necessary directories, startup files, lab.conf and lab.dep files that are required
mkdir m1 m2 r m5 extm1 extm2 

touch m1.startup m2.startup r.startup m5.startup extm1.startup extm2.startup lab.conf lab.dep

#The following commands will input the necessary data into the startup files for each machine
echo "ifconfig eth0 hw ether c0:cc:cc:cc:cc:cc" > m1.startup
echo "ifconfig eth0 192.168.0.3/29" >> m1.startup
echo >> m1.startup
echo "route add default gw 192.168.0.4" >> m1.startup
echo >> m1.startup

echo "ifconfig eth0 hw ether b0:bb:bb:bb:bb:bb" > m2.startup
echo "ifconfig eth0 192.168.0.2/29" >> m2.startup
echo >> m2.startup
echo "route add default gw 192.168.0.4" >> m2.startup
echo >> m2.startup

echo "ifconfig eth0 hw ether 10:11:11:11:11:11" > r.startup
echo "ifconfig eth0 192.168.0.4/29" >> r.startup
echo >> r.startup
echo "ifconfig eth1 10.0.0.1/29" >> r.startup
echo >> r.startup

echo "ifconfig eth0 hw ether a0:aa:aa:aa:aa:aa" > m5.startup
echo "ifconfig eth0 192.168.0.1/29" >> m5.startup
echo >> m5.startup
echo "route add default gw 192.168.0.4" >> m5.startup
echo >> m5.startup

echo "ifconfig eth0 10.0.0.2/29" >> extm1.startup
echo >> extm1.startup
echo "route add default gw 10.0.0.1" >> extm1.startup
echo >> extm1.startup

echo "ifconfig eth0 10.0.0.3/29" >> extm2.startup
echo >> extm2.startup
echo "route add default gw 10.0.0.1" >> extm2.startup
echo >> extm2.startup

#The following commands will input necessary data into the lab.conf file
echo "m1[0]=lan" >> lab.conf
echo "m2[0]=lan" >> lab.conf
echo "r[0]=lan" >> lab.conf
echo "r[1]=notlan" >> lab.conf
echo "m5[0]=lan" >> lab.conf
echo "extm1[0]=notlan" >> lab.conf
echo "extm2[0]=notlan" >> lab.conf

echo "The script has executed and the lab is ready... move into the created directory and type lstart to start the lab"
