#!/bin/bash
#This script is generated by teh Java code and serves the purpose of regenerating the network
#Creator: 1765180

#Creating a directory for the netkit lab
mkdir regenNetwork
cd regenNetwork
echo "Name of the directory that is created: regenNetwork"
echo "Path of the directory created:"
pwd

