#!/bin/bash
#This script is generated by teh Java code and serves the purpose of regenerating the network
#Creator: 1765180

#Creating a directory for the netkit lab
mkdir regenNetwork
cd regenNetwork
echo "Name of the directory that is created: regenNetwork"
echo "Path of the directory created:"
pwd

#The following two commands will create the necessary directories, startup files, lab.conf and lab.dep files that are required
mkdir m1 m2 

touch m1.startup m2.startup lab.conf lab.dep

#The following commands will input the necessary data into the startup files for each machine
echo "ifconfig eth0 hw ether c0:cc:cc:cc:cc:cc" > m1.startup
echo "ifconfig eth0 192.168.0.3/30" >> m1.startup
echo >> m1.startup

echo "ifconfig eth0 hw ether b0:bb:bb:bb:bb:bb" > m2.startup
echo "ifconfig eth0 192.168.0.2/30" >> m2.startup
echo >> m2.startup

#The following commands will input necessary data into the lab.conf file
echo "m1[0]=lan" >> lab.conf
echo "m2[0]=lan" >> lab.conf

echo "The script has executed and the lab is ready... move into the created directory and type lstart to start the lab"
